name: Deploy Next.js to GitHub Pages

# main 브랜치에 push 될 때마다 실행
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 레포지토리 체크아웃
      - uses: actions/checkout@v4

      # 2. Node.js 설치 + Yarn 캐시
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      # 3. Yarn 의존성 설치
      - run: yarn install

      # 4. Next.js 정적 빌드
      - run: yarn build

      # 5. 정적 export (out/ 폴더 생성)
      - run: yarn export

      # 6. GitHub Pages용 아티팩트 업로드
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
